on: [push]
name: benchmark push
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable, nightly ]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: boa-dev/criterion-compare-action@master
        with:
          branchName: ${{ github.base_ref }}